export interface Aria2Options {
    "allow-overwrite": any
    "allow-piece-length-change": any
    "always-resume": any
    "async-dns": any
    "auto-file-renaming": any
    "bt-enable-hook-after-hash-check": any
    "bt-enable-lpd": any
    "bt-force-encryption": any
    "bt-hash-check-seed": any
    "bt-load-saved-metadata": any
    "bt-max-peers": any
    "bt-metadata-only": any
    "bt-min-crypto-level": any
    "bt-remove-unselected-file": any
    "bt-request-peer-speed-limit": any
    "bt-require-crypto": any
    "bt-save-metadata": any
    "bt-seed-unverified": any
    "bt-stop-timeout": any
    "bt-tracker-connect-timeout": any
    "bt-tracker-interval": any
    "bt-tracker-timeout": any
    "check-integrity": any
    "conditional-get": any
    "connect-timeout": any
    "content-disposition-default-utf8": any
    "continue": any
    "dir": any
    "dry-run": any
    "enable-http-keep-alive": any
    "enable-http-pipelining": any
    "enable-mmap": any
    "enable-peer-exchange": any
    "file-allocation": any
    "follow-metalink": any
    "follow-torrent": any
    "force-save": any
    "ftp-pasv": any
    "ftp-reuse-connection": any
    "ftp-type": any
    "hash-check-only": any
    "http-accept-gzip": any
    "http-auth-challenge": any
    "http-no-cache": any
    "lowest-speed-limit": any
    "max-connection-per-server": any
    "max-download-limit": any
    "max-file-not-found": any
    "max-mmap-limit": any
    "max-resume-failure-tries": any
    "max-tries": any
    "max-upload-limit": any
    "metalink-enable-unique-protocol": any
    "metalink-preferred-protocol": any
    "min-split-size": any
    "no-file-allocation-limit": any
    "no-netrc": any
    "parameterized-uri": any
    "pause-metadata": any
    "piece-length": any
    "proxy-method": any
    "realtime-chunk-checksum": any
    "referer": any
    "remote-time": any
    "remove-control-file": any
    "retry-wait": any
    "reuse-uri": any
    "rpc-save-upload-metadata": any
    "save-not-found": any
    "seed-ratio": any
    "seed-time": any
    "split": any
    "stream-piece-selector": any
    "timeout": any
    "uri-selector": any
    "use-head": any
    "user-agent": any
}